In [13]:
import numpy as np

In [14]:
input = """..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@.
""".strip().splitlines()
input

['..@@.@@@@.',
 '@@@.@.@.@@',
 '@@@@@.@.@@',
 '@.@@@@..@.',
 '@@.@@@@.@@',
 '.@@@@@@@.@',
 '.@.@.@.@@@',
 '@.@@@.@@@@',
 '.@@@@@@@@.',
 '@.@.@@@.@.']

In [15]:
with open("input.txt") as f:
    input = [line.strip() for line in f]


In [16]:
array = []
for line in input:
    miniarray = []
    for char in line:
        if char == '@':
            miniarray.append(1)
        else:
            miniarray.append(0)
    array.append(miniarray)

array = np.array(array)
array



array([[1, 1, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 0, 1],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]], shape=(136, 136))

In [17]:
array.shape

(136, 136)

In [18]:
def countarrayfunc(array):
    countarray = np.zeros(array.shape, dtype=int)

    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            counts = 0
            for di in [-1, 0, 1]:
                for dj in [-1, 0, 1]:
                    if di == 0 and dj == 0:
                        continue
                    ni = i + di
                    nj = j + dj
                    if 0 <= ni < array.shape[0] and 0 <= nj < array.shape[1]:
                        counts += array[ni, nj]
            countarray[i, j] = counts
    return countarray
countarray = countarrayfunc(array)
countarray

array([[2, 3, 3, ..., 4, 3, 2],
       [3, 6, 6, ..., 5, 6, 3],
       [3, 5, 3, ..., 5, 6, 3],
       ...,
       [4, 5, 5, ..., 3, 4, 2],
       [4, 5, 7, ..., 5, 8, 4],
       [2, 3, 3, ..., 3, 4, 2]], shape=(136, 136))

In [19]:
def logical_check(array, countarray):
    cnum = np.zeros(array.shape, dtype=int)
    
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            if array[i, j] == 1 and countarray[i, j] < 4:
                cnum[i, j] = 1
    
    c = cnum.sum()
    return c, cnum

c, cnum = logical_check(array, countarray)


In [20]:
cnum

array([[1, 1, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 0, 1]], shape=(136, 136))

In [21]:
sum(sum(cnum))

np.int64(1351)

doing the same with removal

In [22]:
import plotly.express as px
from IPython.display import clear_output, display
import time

fig = px.imshow(array, color_continuous_scale='Agsunset')
fig.show()
startingrolls = sum(sum(array))

while True:
    countarray = countarrayfunc(array)
    c, cnum = logical_check(array, countarray)
    total_new = sum(sum(cnum))

    fig.data[0].z = countarray
    clear_output(wait=True)
    display(fig)
    time.sleep(0.02)
    if total_new == 0:
        print(f"Done : {startingrolls - sum(sum(array))} remaining")
        break
    array = array - cnum

Done : 8345 remaining


3751 too low

In [23]:
sum(sum(array))

np.int64(3751)